/* Automatically generated by bpftool */
#ifndef __VMLINUX_H__
#define __VMLINUX_H__

struct task_struct {
    long state;
    void *stack;
    int prio;
    // ... (수천 라인...,.홓ㅎㅎㅎ생략)
};
#endif /* __VMLINUX_H__ */
